# Generated by Django 5.1 on 2024-08-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_remove_book_cover_img_url_remove_book_published_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="book",
        ),
        migrations.RemoveField(
            model_name="like",
            name="recommendation",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="commented_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="recommended_at",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="book_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="book_title",
            field=models.CharField(default="Unknown Title", max_length=255),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="cover_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="publication_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rating",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.recommendation"
            ),
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
