# Generated by Django 5.1 on 2024-08-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_recommendation_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="link",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
